remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: East House Enrichment Program @ RIT, June 2023
description: This workshop will provide an introduction to core software programming concepts.
relative_links:
  enabled: true
  collections: true
